global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'moria-gate-api'
    static_configs:
      - targets: ['api:8443']
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
